name: Godot Setup
description: Cache and install Godot editor + export templates
inputs:
  godot-version:
    description: Godot version (e.g. 4.6)
    required: true
runs:
  using: composite
  steps:
    - name: Cache Godot
      id: cache-godot
      uses: actions/cache@v4
      with:
        path: |
          ~/godot-bin
          ~/.local/share/godot/export_templates
        key: godot-${{ inputs.godot-version }}-${{ runner.os }}

    - name: Setup Godot
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        GODOT_VERSION="${{ inputs.godot-version }}"
        echo "Setting up Godot $GODOT_VERSION..."

        # Download Godot
        GODOT_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip"
        echo "Downloading from: $GODOT_URL"

        if ! curl -f -L -o godot.zip "$GODOT_URL"; then
          echo "❌ ERROR: Failed to download Godot $GODOT_VERSION"
          exit 1
        fi

        unzip -q godot.zip
        mkdir -p ~/godot-bin
        mv "Godot_v${GODOT_VERSION}-stable_linux.x86_64" ~/godot-bin/godot
        chmod +x ~/godot-bin/godot
        ~/godot-bin/godot --version

        # Download export templates
        TEMPLATES_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
        echo "Downloading templates from: $TEMPLATES_URL"

        if ! curl -f -L -o export_templates.tpz "$TEMPLATES_URL"; then
          echo "❌ ERROR: Failed to download export templates"
          exit 1
        fi

        unzip -q export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
        mv templates/* ~/.local/share/godot/export_templates/$GODOT_VERSION.stable/

        echo "✅ Successfully installed Godot $GODOT_VERSION and export templates"

    - name: Add Godot to PATH
      shell: bash
      run: echo "$HOME/godot-bin" >> $GITHUB_PATH
