name: Godot Export
description: Import project and export a build for a platform
inputs:
  project-path:
    description: Path to the Godot project
    required: true
  preset:
    description: Export preset name
    required: true
  export-dir:
    description: Output directory
    required: true
  export-file:
    description: Output file name (or .app directory for macOS)
    required: true
  platform:
    description: Platform key (windows/linux/macos/web)
    required: true
runs:
  using: composite
  steps:
    - name: Import Project Files
      shell: bash
      run: |
        PROJECT_PATH="${{ inputs.project-path }}"
        echo "Importing project files..."
        godot --headless --editor --quit --import --path "./$PROJECT_PATH"

    - name: Export Build
      shell: bash
      run: |
        PROJECT_PATH="${{ inputs.project-path }}"
        EXPORT_DIR="${{ inputs.export-dir }}"
        EXPORT_FILE="${{ inputs.export-file }}"
        PLATFORM="${{ inputs.platform }}"

        mkdir -p "$EXPORT_DIR"
        echo "Exporting $PLATFORM build to: $EXPORT_DIR"

        godot --headless --path "./$PROJECT_PATH" --export-release "${{ inputs.preset }}" "$EXPORT_DIR/$EXPORT_FILE"

        if [ "$PLATFORM" = "macos" ]; then
          if [ ! -d "$EXPORT_DIR/$EXPORT_FILE" ]; then
            echo "❌ $PLATFORM export failed - file not found at $EXPORT_DIR/$EXPORT_FILE"
            echo "Contents of export directory:"
            ls -la "$EXPORT_DIR/" || echo "Directory does not exist!"
            exit 1
          fi
        else
          if [ ! -f "$EXPORT_DIR/$EXPORT_FILE" ]; then
            echo "❌ $PLATFORM export failed - file not found at $EXPORT_DIR/$EXPORT_FILE"
            echo "Contents of export directory:"
            ls -la "$EXPORT_DIR/" || echo "Directory does not exist!"
            exit 1
          fi
        fi

        echo "✅ $PLATFORM export completed successfully"
        ls -la "$EXPORT_DIR/"
