name: Detect Godot Config
description: Detect project path, Godot version, game name, and export presets
inputs:
  project-path-default:
    description: Default project folder to check first
    required: false
    default: forest-survival-multiplayer
outputs:
  godot-version:
    description: Detected Godot version
    value: ${{ steps.detect.outputs.godot-version }}
  game-name:
    description: Detected game name (normalized)
    value: ${{ steps.detect.outputs.game-name }}
  project-path:
    description: Path containing project.godot
    value: ${{ steps.detect.outputs.project-path }}
  has-platforms:
    description: Whether export presets were found
    value: ${{ steps.matrix.outputs.has-platforms }}
  matrix:
    description: JSON matrix include list
    value: ${{ steps.matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Detect Project Configuration
      id: detect
      shell: bash
      run: |
        echo "Detecting project configuration from project.godot..."

        DEFAULT_PATH="${{ inputs.project-path-default }}"

        # Find project.godot location
        if [ -f "$DEFAULT_PATH/project.godot" ]; then
          PROJECT_PATH="$DEFAULT_PATH"
        elif [ -f "project.godot" ]; then
          PROJECT_PATH="."
        else
          echo "❌ ERROR: Could not find project.godot"
          exit 1
        fi

        echo "Found project at: $PROJECT_PATH"

        GODOT_VERSION=$(grep 'config/features' "$PROJECT_PATH/project.godot" | grep -o '[0-9]\+\.[0-9]\+' | head -n 1)

        if [ -z "$GODOT_VERSION" ]; then
          echo "❌ ERROR: Could not detect Godot version from project.godot"
          exit 1
        fi

        GAME_NAME=$(grep 'config/name=' "$PROJECT_PATH/project.godot" | sed 's/config\/name="\(.*\)"/\1/' | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | tr -d ':' || echo "godot-game")

        echo "godot-version=$GODOT_VERSION" >> $GITHUB_OUTPUT
        echo "game-name=$GAME_NAME" >> $GITHUB_OUTPUT
        echo "project-path=$PROJECT_PATH" >> $GITHUB_OUTPUT

        echo "Detected configuration:"
        echo "  Project Path: $PROJECT_PATH"
        echo "  Godot Version: $GODOT_VERSION"
        echo "  Game Name: $GAME_NAME"

    - name: Detect Export Presets & Set Matrix
      id: matrix
      shell: bash
      run: |
        echo "Detecting configured export presets..."

        PROJECT_PATH="${{ steps.detect.outputs.project-path }}"
        GAME_NAME="${{ steps.detect.outputs.game-name }}"

        # Check if export_presets.cfg exists
        if [ ! -f "$PROJECT_PATH/export_presets.cfg" ]; then
          echo "⚠️ WARNING: export_presets.cfg not found in $PROJECT_PATH"
          echo "Please configure export presets in Godot Editor (Project → Export)"
          echo "has-platforms=false" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[]}" >> $GITHUB_OUTPUT
          exit 0
        fi

        declare -A platforms=(
          ["windows"]="Windows Desktop|windows|${GAME_NAME}.exe"
          ["linux"]="Linux|linux|${GAME_NAME}.x86_64"
          ["web"]="Web|web|index.html"
          ["macos"]="macOS|macos|${GAME_NAME}.app"
        )

        matrix_include="["
        platform_count=0

        for platform in "${!platforms[@]}"; do
          IFS='|' read -ra PLATFORM_INFO <<< "${platforms[$platform]}"
          preset_name="${PLATFORM_INFO[0]}"
          folder_name="${PLATFORM_INFO[1]}"
          file_name="${PLATFORM_INFO[2]}"

          if grep -q "platform=\"$preset_name\"" "$PROJECT_PATH/export_presets.cfg"; then
            echo "✅ Found preset for $platform ($preset_name)"

            if [ $platform_count -gt 0 ]; then
              matrix_include+="," 
            fi

            matrix_include+="{\"platform\":\"$platform\",\"preset\":\"$preset_name\",\"folder\":\"$folder_name\",\"file\":\"$file_name\"}"
            platform_count=$((platform_count + 1))
          else
            echo "❌ No preset found for $platform ($preset_name)"
          fi
        done

        matrix_include+="]"

        if [ $platform_count -eq 0 ]; then
          echo "No export presets found!"
          echo "has-platforms=false" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[]}" >> $GITHUB_OUTPUT
        else
          echo "Found $platform_count platform(s) to export"
          echo "has-platforms=true" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":$matrix_include}" >> $GITHUB_OUTPUT
        fi

        echo "Matrix: {\"include\":$matrix_include}"
